//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterTb
    {
        public int EnvanterID { get; set; }
        public string Sube { get; set; }
        public string Lokasyon { get; set; }
        public string EnvanterCinsi { get; set; }
        public string EnvanterMarka { get; set; }
        public string EnvanterModel { get; set; }
        public string EnvanterSeriNo { get; set; }
        public string EnvanterOzellik { get; set; }
    }
}
