//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka
    {
        public int MarkaID { get; set; }
        public string MarkaAdi { get; set; }
    }
}
