//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OzdilekBtServisTakipEntities : DbContext
    {
        public OzdilekBtServisTakipEntities()
            : base("name=OzdilekBtServisTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EnvanterCinsi> EnvanterCinsi { get; set; }
        public DbSet<EnvanterTb> EnvanterTb { get; set; }
        public DbSet<Firma> Firma { get; set; }
        public DbSet<KullaniciTb> KullaniciTb { get; set; }
        public DbSet<Lokasyon> Lokasyon { get; set; }
        public DbSet<Marka> Marka { get; set; }
        public DbSet<ServisGelenTb> ServisGelenTb { get; set; }
        public DbSet<ServisTb> ServisTb { get; set; }
        public DbSet<Sube> Sube { get; set; }
    }
}
