//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzdilekBtServisTakipPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisTb
    {
        public int ServisID { get; set; }
        public int EnvanterID { get; set; }
        public string Sube { get; set; }
        public string Lokasyon { get; set; }
        public string ServisCinsi { get; set; }
        public string ServisMarka { get; set; }
        public string ServisModel { get; set; }
        public string ServisSeriNo { get; set; }
        public string ServisOzellik { get; set; }
        public string GonderenKisi { get; set; }
        public string GonderildigiTarih { get; set; }
        public string EkAksesuar { get; set; }
        public string ArizaSebebi { get; set; }
        public string ServisDurumu { get; set; }
        public string ServisFirma { get; set; }
    }
}
